#ifndef __SLAVE_REGISTERS_H__
#define __SLAVE_REGISTERS_H__

// A list of slave registers and their offsets
#define SLAVE_TYPE          		0x0
#define SLAVE_TYPE_SIZE     		1

#define SLAVE_REVISION      		0x1
#define SLAVE_REVISION_SIZE 		1

#define SLAVE_BUILD         		0x2
#define SLAVE_BUILD_SIZE        	2

#define SLAVE_SUPPORTED_FMMU    	0x4
#define SLAVE_SUPPORTED_FMMU_SIZE 	1

#define SLAVE_SUPPORTED_SM			0x5
#define SLAVE_SUPPORTED_SM_SIZE		1

#define SLAVE_RAM_SIZE				0x6
#define SLAVE_RAM_SIZE_SIZE			1

#define SLAVE_PORT_DESCRIPTOR		0x7
#define SLAVE_PORT_DESCRIPTOR_SIZE  1

#define SLAVE_ESC_FEATURES			0x8
#define SLAVE_ESC_FEATURES_SIZE		2
// Gap?
#define SLAVE_STATION_ADDR			0x10
#define SLAVE_STATION_ADDR_SIZE		2

// Station alias is ignored by default (ESC_DL_CONTROL bit 24)
#define SLAVE_STATION_ALIAS			0x12
#define SLAVE_STATION_ALIAS_SIZE	2

#define SLAVE_WRITE_REG_ENABLE		0x20
#define SLAVE_WRITE_REG_ENABLE_SIZE	1

#define SLAVE_WRITE_REG_PROT		0x21
#define SLAVE_WRITE_REG_PROT_SIZE	1

#define SLAVE_WRITE_ESC_ENABLE		0x30
#define SLAVE_WRITE_ESC_ENABLE_SIZE	1

#define SLAVE_WRITE_ESC_PROT		0x31
#define SLAVE_WRITE_ESC_PROT_SIZE	1

#define SLAVE_ESC_RESET_ECAT		0x40
#define SLAVE_ESC_RESET_ECAT_SIZE	1

#define SLAVE_ESC_RESET_PDI			0x41
#define SLAVE_ESC_RESET_PDI_SIZE	1

#define SLAVE_AL_CONTROL			0x120
#define SLAVE_AL_CONTROL_SIZE		2
// Register map is the same as the status reg below

#define SLAVE_AL_STATUS 			0x130
#define SLAVE_AL_STATUS_SIZE		2
#define SLAVE_AL_STATE_MASK  0xF
#define SLAVE_AL_STATE_INIT  0x1
#define SLAVE_AL_STATE_PREOP 0x2
#define SLAVE_AL_STATE_SAFEOP 0x4
#define SLAVE_AL_STATE_OP    0x8
#define SLAVE_AL_ERROR_IND   0x10

#define SLAVE_AL_STATUS_CODE      0x134
#define SLAVE_AL_STATUS_CODE_SIZE 2

#define SLAVE_AL_ERROR_MASK  (0x1 << 4)
#define SLAVE_AL_IDENT_MASK  (0x1 << 5)

#define SLAVE_PDI_CONTROL           0x140
#define SLAVE_PDI_CONTROL_SIZE      1

#define SLAVE_ECAT_EVENT_REQUEST	0x210
#define SLAVE_ECAT_EVENT_REQUEST_SIZE 2
#define SLAVE_ECAT_EVENT_DCLATCH_MASK (0x1 << 0)
#define SLAVE_ECAT_EVENT_DLSTATUS_MASK (0x1 << 2)
#define SLAVE_ECAT_EVENT_ALSTATUS_MASK (0x1 << 3)


#define SLAVE_EEPROM_CONTROL		0x502
#define SLAVE_EEPROM_CONTROL_SIZE	2
#define SLAVE_EEPROM_CONTROL_COMMAND_MASK   (0x7 << 8)
#define SLAVE_EEPROM_CONTROL_COMMAND_IDLE   (0 << 8)
#define SLAVE_EEPROM_CONTROL_COMMAND_READ   (1 << 8)
#define SLAVE_EEPROM_CONTROL_COMMAND_WRITE  (2 << 8)
#define SLAVE_EEPROM_CONTROL_COMMAND_RELOAD (4 << 8)

#define SLAVE_EEPROM_ADDRESS		0x504
#define SLAVE_EEPROM_ADDRESS_SIZE	4

// TODO: Make this configurable. It's 4 bytes on ESC20, 8 on others.
#define SLAVE_EEPROM_DATA			0x508
#define SLAVE_EEPROM_DATA_SIZE		4

#define FMMU_ADDR(base, index) (base + SLAVE_FMMU_OFFSET*index)
#define SLAVE_FMMU_BASE              0x600
#define SLAVE_FMMU_OFFSET            16
#define SLAVE_FMMU_LOGICAL_START     0x600
#define SLAVE_FMMU_LENGTH            0x604
#define SLAVE_FMMU_LOGICAL_START_BIT 0x606
#define SLAVE_FMMU_LOGICAL_STOP_BIT  0x607
#define SLAVE_FMMU_PHYSICAL_START    0x608
#define SLAVE_FMMU_PHYSICAL_START_BIT 0x60A
#define SLAVE_FMMU_TYPE              0x60B
#define SLAVE_FMMU_ACTIVATE          0x60C

#define SLAVE_FMMU_TYPE_READ_MASK    0x1
#define SLAVE_FMMU_TYPE_WRITE_MASK   0x2

#define SLAVE_FMMU_ACTIVATE_ACTIVE_MASK 0x1

#define SYNCMANAGER_ADDR(base, index) (base + SLAVE_SYNCMANAGER_OFFSET*index)
#define SLAVE_SYNCMANAGER_BASE      0x800
#define SLAVE_SYNCMANAGER_OFFSET    8    // This is what to add for syncmanager x
#define SLAVE_SYNCMANAGER_STARTADDR 0x800
#define SLAVE_SYNCMANAGER_LENGTH    0x802
#define SLAVE_SYNCMANAGER_CONTROL	0x804
#define SLAVE_SYNCMANAGER_STATUS	0x805
#define SLAVE_SYNCMANAGER_ACTIVATE	0x806
#define SLAVE_SYNCMANAGER_PDI		0x807

#define SLAVE_SYNCMANAGER_CONTROL_OPMODE_MASK 0x3
#define SLAVE_SYNCMANAGER_CONTROL_OPMODE_BUFFERED 0
#define SLAVE_SYNCMANAGER_CONTROL_OPMODE_MAILBOX 2

#define SLAVE_SYNCMANAGER_CONTROL_DIRECTION_MASK (0x3 << 2)
#define SLAVE_SYNCMANAGER_CONTROL_DIRECTION_READ (0x0 << 2)  // ECAT read, PDI write
#define SLAVE_SYNCMANAGER_CONTROL_DIRECTION_WRITE (0x1 << 2) // ECAT write, PDI read

#define SLAVE_SYNCMANAGER_CONTROL_INTR_ECAT_MASK (0x1 << 4)
#define SLAVE_SYNCMANAGER_CONTROL_INTR_PDI_MASK  (0x1 << 5)
#define SLAVE_SYNCMANAGER_CONTROL_WATCHDOG_MASK  (0x1 << 6)

#define SLAVE_SYNCMANAGER_STATUS_MAILBOX_FULL_MASK (0x1 << 3)

#define SLAVE_SYNCMANAGER_ACTIVATE_ACTIVE_MASK (0x1 << 0)
#define SLAVE_SYNCMANAGER_ACTIVATE_ECAT_LATCH_MASK (0x1 << 6)
#define SLAVE_SYNCMANAGER_ACTIVATE_PDI_LATCH_MASK  (0x1 << 7)

#endif
